---
- name: Install mysql
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
   - python-mysqldb
  become: true

- name: Start mysql service
  service: 
    name: mysql
    state: started
    enabled: yes
  become: true
