---
- name: Install Apache
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - php5
    - python-mysqldb
    - git 
  become: true

- name: Start Apache
  service: 
    name: apache2
    state: started
    enabled: yes    
  become: true
